### PR TITLE
Added updateable plots

### PR DESCRIPTION
**Pull request by ShoofLLC**
The plot class can now be used to show a single window where the plot would be dynamically updated. 

This is not the cleanest implementation but it kinda works and I have tested it locally. This may need more work to be ready for a release.

### CODE REVIEW

**Comment by HorstBaerbel** [comment]
Thanks for you contribution. Could you make an example file and push that?

**Comment by ShoofLLC** [comment]
> Thanks for you contribution. Could you make an example file and push that?

Done

**Comment by ShoofLLC** [comment]
The pipe popen function has to be different for windows, I can try and look for the windows equivalent of this.

**Comment by HorstBaerbel** [comment]
Yes. It should work on all three OSes...

**Comment by ShoofLLC** [comment]
Ok it works on a windows machine as well with gnuplot -- mingw, if we could trigger the workflow again it should be green

**Comment by ShoofLLC** [comment]
[osx](https://github.com/ShoofLLC/sciplot/actions/workflows/osx.yml)
[linux](https://github.com/ShoofLLC/sciplot/actions/workflows/linux.yml)
[windows](https://github.com/ShoofLLC/sciplot/actions/workflows/windows.yml)

**Comment by HorstBaerbel** [comment]
Thanks again. It seems the same for Plo3D is missing. Also I'm not sure how it interacts with multiplot / figures, need to do some more tests and it needs some cleaning (NULL->nullptr etc.). I can do that when I find time and will merge then...

**Comment by Nelson-numerical-software** [comment]
> Ok it works on a windows machine as well with gnuplot -- mingw, if we could trigger the workflow again it should be green

!!! Warning "popen" with Visual studio.
See: https://docs.microsoft.com/fr-fr/cpp/c-runtime-library/reference/popen-wpopen?view=msvc-160

**Pull request merged**
